### ISSUE TITLE
Not possible to login

### ISSUE THREAD

**Issue by FireWizard52** [hardillb/node-red-contrib-googlehome-web#20]
Hi,

I have signed up at: https://googlehome.hardill.me.uk/
I created a login name and password and was able to create a device.

However after logging out it is impossible to login again.

Also in the Google Home app it continues to tell me: wrong username or password.

Trying to reset the password does not work either.
Clicking on the received link gives me: Cannot GET /changePassword/< the received link>

**Comment by hardillb** [comment]
Hi,

Thanks for letting me know.

The problem with the password reset is a section missing out of the path. I'll push a fix for that this evening, but for now, if you copy paste the URL and insert a `/user` before `/changePassword`

    https://googlehome.hardill.me.uk/user/changePassword/<code>

It  should work.

As for the initial password, I'm going to guess you have special char in the password e.g. a `:` I think there is an escaping problem somewhere in the password checking code I need to track down.

Can you let me know your username so I can look in the logs (Don't worry I have no access to the uncrypted passwords, but I'd like to check a few things)

**Comment by FireWizard52** [comment]
Hi,

Thanks for the response.

The username is Herman_Jalink.
Perhaps the underscore is the problem?

But Iḿ a little bit confused as I also found:
https://red.cb-net.co.uk/

What is the relation?
I was able to sign in  at that site. It gives me the same possibilities.
And it has been added to my Google Home app.

**Comment by hardillb** [comment]
https://red.cb-net.co.uk/ is a fork of my other [project](https://github.com/hardillb/node-red-alexa-home-skill-web) (that supplies the same features for Amazon Alexa) it has nothing to do with me or my nodes.

Unfortunately the author decided to fork my project rather than work with me to improve the original.

**Comment by FireWizard52** [comment]
Hi,

Thank you
Ans indeed with

`https://googlehome.hardill.me.uk/user/changePassword/<code>`

I have been able to log in again

**Comment by FireWizard52** [comment]
And in Node Red it looks OK as well,

Thanks again

**Comment by the-make-r** [comment]
Hi, I have the same problem as @FireWizard52 . The only thong that is different is that I can change the password, but login off and on again doesn't work

**Comment by hardillb** [comment]
@the-make-r you can't have the same problem as this issue is about a missing path section in the password reset email and that has been fixed. In future please do not use closed issues to report new problems, open a new issue and reference any closed issues you think are relevant.

Also you've not supplied any of the information that would help me work out why can't log in.

 - What is your usename on the system?
 - And are there any special characters in your password? specifically `@`
